# Generated by Django 4.0.2 on 2022-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
