# Generated by Django 4.0.2 on 2022-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=70)),
            ],
        ),
    ]
