# Generated by Django 4.0.2 on 2022-02-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_contect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contect',
        ),
    ]
